import pandas as pd
from pathlib import Path

def inspect_paderborn_parquet(file_path):
    """
    Loads a Paderborn parquet file and prints its structure and a few rows.
    """
    print(f"--- Inspecting: {file_path} ---")
    
    # Load the parquet file
    df = pd.read_parquet(file_path)
    
    # Print the schema/info
    print("\nDataFrame Info:")
    df.info()
    
    # Print the first few rows
    print("\nFirst 2 rows of data:")
    # We only show a couple of rows because the arrays can be very large in the terminal
    print(df.head(2))
    print(df.shape)
    
    # Show array shapes for the first row to demonstrate the signal data
    first_row = df.iloc[0]
    print("\nSignal Array Shapes (First Row):")
    print(f"speed array shape: {first_row['speed'].shape}")
    print(f"vibration array shape: {first_row['vibration'].shape}")
    print("-" * 40)

if __name__ == "__main__":
    # Example usage: point to one of the generated parquet files
    # We use K001.parquet as an example which should be generated by paderborn_download.py
    sample_file = Path("../data/Paderborn/interim/KA01.parquet")
    
    if sample_file.exists():
        inspect_paderborn_parquet(sample_file)
    else:
        print(f"File not found: {sample_file}")
        print("Make sure you have run paderborn_download.py first.")
